apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 3000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000