apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: development
  labels:
    app: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-service
        image: farhandockerk8/simple-microservice-example-api:v1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: api-configmap
        readinessProbe:
          httpGet:
            path: /api/status
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/status
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - api-gateway
            topologyKey: "kubernetes.io/hostname"