apiVersion: apps/v1
kind: Deployment
metadata:
  name: qoute-deployment
  labels:
    app: qoute-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qoute
  template:
    metadata:
      labels:
        app: qoute
    spec:
      containers:
      - name: qoute-micro-service
        image: farhandockerk8/simple-microservice-example-quotes:v1
        ports:
        - containerPort: 5000