apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: quote
  ports:
    - port: 5000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000
  sessionAffinity: ClientIP