apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-deployment
  labels:
    app: quote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote-micro-service
        image: farhandockerk8/simple-microservice-example-quotes:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: api-configmap
        readinessProbe:
          httpGet:
            path: /api/quote
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/quote
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - quote
            topologyKey: "kubernetes.io/hostname"