apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-app
  namespace: development
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "5Gi"
    limits.cpu: "6"
    limits.memory: "10Gi"